echo --------------------------- Stopping and removing ACTUAL containers...
docker-compose down -v
echo --------------------------- Removing network...
docker network rm monitoring_logging
echo --------------------------- Output from \'docker ps -a\'...
docker ps -a
echo --------------------------- Output from \'docker volume ls\'...
docker volume ls
echo --------------------------- Output from \'docker network ls\'...
docker network ls
echo ---------------------------To remove orphaned volumes run $: docker volume rm $(docker volume ls -qf dangling=true)
